version: '2.13'
services:
  db:
    container_name: pg_container
    image: postgres:14-alpine
    restart: always
    env_file:
      - ./.env
    environment:
      POSTGRES_USER: "${DB_USER}"
      POSTGRES_PASSWORD: "${DB_PASS}"
      POSTGRES_DB: "${DB_NAME}"
    volumes:
      - myapp:/postgres_data/var/lib/postgresql/data
    ports:
      - "54321:5432"
  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    env_file:
      - ./.env
    environment:
      PGADMIN_DEFAULT_EMAIL: "${PGADMIN_DEFAULT_EMAIL}"
      PGADMIN_DEFAULT_PASSWORD: "${PGADMIN_DEFAULT_PASSWORD}"
    ports:
      - "5050:80"
  redis:
    image: redis
    ports:
      - "6379:6379"
    command: redis-server
volumes:
  myapp:

