version: '2.13'
services:
  db:
    container_name: pg_container
    image: postgres:14-alpine
    restart: always
    env_file:
      - .envsss
    environment:
      POSTGRES_USER: "${DB_USER}"
      POSTGRES_PASSWORD: "${DB_PASS}"
      POSTGRES_DB: "${DB_NAME}"
    volumes:
      - myapp:/postgres_data/var/lib/postgresql/data
    ports:
      - "54321:5432"
  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    env_file:
      - .envsss
    environment:
      PGADMIN_DEFAULT_EMAIL: "${PGADMIN_DEFAULT_EMAIL}"
      PGADMIN_DEFAULT_PASSWORD: "${PGADMIN_DEFAULT_PASSWORD}"
    ports:
      - "5050:80"
  rabbitmq_todo:
    image: rabbitmq:3.8-management
    ports:
      - 5672:5672  # порт для доступа к RabbitMQ
      - 15672:15672  # порт для доступа к RabbitMQ Management UI
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq  # сохранение данных RabbitMQ
    environment:
      - RABBITMQ_DEFAULT_USER=admin  # имя пользователя для RabbitMQ
      - RABBITMQ_DEFAULT_PASS=admin123  # пароль для RabbitMQ
volumes:
  myapp:
  rabbitmq_data:

